
###
#Login User
#
POST http://localhost:5000/api/auth/users/login
accept: */*
Content-Type: application/json-patch+json

{
  "userName": "Delphiguy",
  "password": "Nescafe3in!",
  "email": "randy@kodelev8.com",
  "tenantId": 1
}

###
# curl -X 'GET'
#  'http://localhost:5000/api/auth/users/all'
#  -H 'accept: */*'
#  -H 'Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJyYW5keUBrb2RlbGV2OC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiQWRhbnphIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiUmFuZHkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiREVMUEhJR1VZIiwiaHR0cDovL2tvZGVsZXY4LmNvbS91c2VyaWQiOiJkMzIyZDhjZC03MjE0LTRjYjktOTYwMy04YjFhZTIzYjg2NWQiLCJodHRwOi8va29kZWxldjguY29tL3VzZXJ0eXBlIjoidXNlciIsImh0dHA6Ly9rb2RlbGV2OC5jb20vdGVuYW50IjoiMSIsImh0dHA6Ly9rb2RlbGV2OC5jb20vYWNjZXNzcm9sZXMiOlsicmVhZCIsIndyaXRlIiwiZGVsZXRlIl0sIm5iZiI6MTY5NDkxNDQ4MiwiZXhwIjoxNjk1MDAwODgyLCJpc3MiOiJrb2RlbGV2OC1wb3Mtc2VydmljZS1rb2RlbGV2OC1wb3Mtc2VydmljZSIsImF1ZCI6ImtvZGVsZXY4LXBvcy1zZXJ2aWNlIn0.1RBtJzZ44_AIbee8QgFwY1eK7UJ19z14LGcttHEdTC4'
GET http://localhost:5000/api/auth/users/all
accept: */*
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJyYW5keUBrb2RlbGV2OC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiQWRhbnphIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiUmFuZHkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiREVMUEhJR1VZIiwiaHR0cDovL2tvZGVsZXY4LmNvbS91c2VyaWQiOiJkMzIyZDhjZC03MjE0LTRjYjktOTYwMy04YjFhZTIzYjg2NWQiLCJodHRwOi8va29kZWxldjguY29tL3VzZXJ0eXBlIjoidXNlciIsImh0dHA6Ly9rb2RlbGV2OC5jb20vdGVuYW50IjoiMSIsImh0dHA6Ly9rb2RlbGV2OC5jb20vYWNjZXNzcm9sZXMiOlsicmVhZCIsIndyaXRlIiwiZGVsZXRlIl0sIm5iZiI6MTY5NDkxNDQ4MiwiZXhwIjoxNjk1MDAwODgyLCJpc3MiOiJrb2RlbGV2OC1wb3Mtc2VydmljZS1rb2RlbGV2OC1wb3Mtc2VydmljZSIsImF1ZCI6ImtvZGVsZXY4LXBvcy1zZXJ2aWNlIn0.1RBtJzZ44_AIbee8QgFwY1eK7UJ19z14LGcttHEdTC4
